# Generated by Django 4.2.7 on 2023-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='transitions',
            field=models.IntegerField(blank=True, verbose_name='site transitions'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='volume',
            field=models.FloatField(blank=True, verbose_name='data volume'),
        ),
    ]
