# Generated by Django 4.2.7 on 2023-11-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnsite', '0002_alter_statistics_transitions_alter_statistics_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='transitions',
            field=models.IntegerField(default=0, verbose_name='site transitions'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='volume',
            field=models.FloatField(default=0, verbose_name='data volume'),
        ),
    ]
